### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by flexibility2** [luoyetx/Joint-Face-Detection-and-Alignment#13]
您好，我把您的 “layers”文件夹的层复制到我的caffe里面编译的时候，会报错：
error: ‘class caffe::LayerParameter’ has no member named ‘jfda_loss_param’
请问您知道该怎么解决吗？谢谢！

**Comment by linxiermx** [comment]
> 您好，我把您的“层”文件夹的层复制到我的caffe里面编译的时候，会报错：
> 错误：'class caffe :: LayerParameter'没有名为'jfda_loss_param'的成员请问
> 您知道该怎么解决吗？谢谢！

您好，我也遇到了同样的问题，请问您解决了吗？谢谢！
