### ISSUE TITLE
data layer data queue

### ISSUE THREAD

**Issue by ForestWang** [luoyetx/Joint-Face-Detection-and-Alignment#4]
Hi luoyetx:
thank you for your wonderful work and open source!
 def set_batch_num(self, n1, n2, n3, n4):
    '''set data type number
    # n1 for negatives, n2 for positives, n3 for part faces, n4 for landmark faces
    net_input_size for network input size (width, height)

  def set_data_queue(self, queue):
    '''the queue should put a minibatch with size of (**positives, negative**s, part faces, landmark faces) =
    (n1, n2, n3, n4) in a dict
    '''
so which one is correct, look through the code, negative is n1,and positive is n2, is it right?
Forest

**Comment by luoyetx** [comment]
some mistakes on code comment, n1 is for negative, view [here](https://github.com/luoyetx/Joint-Face-Detection-and-Alignment/blob/master/jfda/minibatch.py#L83) and [here](https://github.com/luoyetx/Joint-Face-Detection-and-Alignment/blob/master/layers/jfda_loss_layer.cpp#L92)
