### ISSUE TITLE
Face Alignment

### ISSUE THREAD

**Issue by haloxhanner** [luoyetx/Joint-Face-Detection-and-Alignment#5]
I can not see any explanation about Face Alignment. It this project can align the faces? Could you provide some details please?

**Comment by luoyetx** [comment]
model gives 5 landmark

**Comment by haloxhanner** [comment]
Okay, I already got it but how can I align the faces using these 5 points? Is this repo can provide it?

**Comment by luoyetx** [comment]
This repo won't provide this function, you may refer to [deepinsight/insightface](https://github.com/deepinsight/insightface).

**Comment by haloxhanner** [comment]
Thank you so much!
