### ISSUE TITLE
图像flip问题

### ISSUE THREAD

**Issue by oftenliu** [luoyetx/Joint-Face-Detection-and-Alignment#9]
minibatch.py的_make_transform成员在做flip时，bbox坐标的变换是否有问题，应该为bbox[0], bbox[2] =1 -bbox[2], 1-bbox[0]

**Comment by luoyetx** [comment]
没有问题，这个 delta_bbox 的 offse 自己在纸上画一下就知道了

**Comment by oftenliu** [comment]
恩　　是的　　你的bbox_target右下角坐标处理的和我的不一样
